### ISSUE TITLE
Issue in fetching variables from GitHub PR Commit message

### ISSUE THREAD

**Issue by vishalmaheswari** [icheko/jenkins-shared-lib#1]
Below is my Jenkins file

######################################
@Library('Jenkins-Library') _

pipeline {
    agent any
    stages {
        stage('AssumeRole') {
            agent any
            steps { 
                // Code For getting Commit Message and AssumeRole goes here
                script {
                    env.account = readCommitVar('vpc')
                    //env.operatingsystem = readCommitVar('os')
                
                    println env.account
                    //println operatingsystem
                }
            }
        }
    }
}

####################################

While raising a PR i provide gitHub commit message as "/vpc:preprod"

Now when the build takes place i get the following. Its not able to fetch the value from commit message

I have truncated the message of checking out the repository and the jenkins pipeline repository
######################

First time build. Skipping changelog.
[Pipeline] withEnv
[Pipeline] {
[Pipeline] script
[Pipeline] {
[Pipeline] sh
+ git log -1 --pretty=%B
[Pipeline] echo
null
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline

###################

Do you know if I am missing something

**Comment by icheko** [comment]
Hi - please confirm you are able to run ```git log -1 --pretty=%B``` command from the Jenkins agent (make sure you run it from the working directory). The log says it's returning null so this library is unable to parse the commit message.
