### ISSUE TITLE
java.lang.IllegalStateException: No KubernetesSlave is set

### ISSUE THREAD

**Issue by raghu-murugesan-e2978** [icheko/jenkins-shared-lib#2]
while using `yaml mergePodTemplates('node-10,sonar-scanner,veracode')` 
and when we are building the Pod using template `Pod pod = new PodTemplateBuilder(parent).build();` we get below error
```
java.lang.IllegalStateException: No KubernetesSlave is set
	at org.csanchez.jenkins.plugins.kubernetes.PodTemplateBuilder.build(PodTemplateBuilder.java:187)
```

**Comment by icheko** [comment]
I committed the latest version I’m using. Does that fix it for you?

**Comment by raghu-murugesan-e2978** [comment]
works like charm, closing the issue.
